import { FormEvent, useEffect, useMemo, useState } from 'react';
import { neon } from './lib/neon';
import './community.css';

type Neighborhood={id:string;name:string};
type Property={id:string;name:string;neighborhood_id:string|null};
type CommunityDashboard={neighborhood_id:string;name:string;active_properties:number;community_cameras:number;online_cameras:number;open_maintenance:number;private_device_sharing_allowed:boolean};
type CommunityDevice={device_id:string;name:string;device_type:string;status:string;latitude:number|null;longitude:number|null;last_seen_at:string|null};
type Maintenance={id:string;device_id:string;device_name:string;title:string;description:string|null;priority:string;status:string;assigned_user_id:string|null;created_at:string;updated_at:string};
type Participant={property_id:string;property_name:string;status:string;route_points_enabled:boolean;community_alerts_enabled:boolean;activated_at:string};
type PathPoint={sequence_no:number;point_type:string;device_id:string|null;name:string;status:string;latitude:number;longitude:number};

export function CommunityCenter(){
  const[neighborhoods,setNeighborhoods]=useState<Neighborhood[]>([]);const[properties,setProperties]=useState<Property[]>([]);const[selectedNeighborhood,setSelectedNeighborhood]=useState('');const[selectedProperty,setSelectedProperty]=useState('');const[dashboard,setDashboard]=useState<CommunityDashboard|null>(null);const[devices,setDevices]=useState<CommunityDevice[]>([]);const[maintenance,setMaintenance]=useState<Maintenance[]>([]);const[participants,setParticipants]=useState<Participant[]>([]);const[path,setPath]=useState<PathPoint[]>([]);const[routeDevice,setRouteDevice]=useState('');const[routeSequence,setRouteSequence]=useState(10);const[maintenanceDevice,setMaintenanceDevice]=useState('');const[maintenanceTitle,setMaintenanceTitle]=useState('');const[maintenanceDescription,setMaintenanceDescription]=useState('');const[maintenancePriority,setMaintenancePriority]=useState('attention');const[routeEnabled,setRouteEnabled]=useState(true);const[alertsEnabled,setAlertsEnabled]=useState(true);const[communityEventsVisible,setCommunityEventsVisible]=useState(true);const[communityRouteEnabled,setCommunityRouteEnabled]=useState(true);const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);
  const propertyOptions=useMemo(()=>properties.filter(p=>!selectedNeighborhood||p.neighborhood_id===selectedNeighborhood),[properties,selectedNeighborhood]);const cameras=devices.filter(d=>d.device_type==='camera');
  async function loadBase(){const[n,p]=await Promise.all([neon.from('neighborhoods').select('id,name'),neon.from('properties').select('id,name,neighborhood_id')]);if(!n.error){const rows=(n.data||[]) as Neighborhood[];setNeighborhoods(rows);setSelectedNeighborhood(v=>v||rows[0]?.id||'')}if(!p.error){const rows=(p.data||[]) as Property[];setProperties(rows);setSelectedProperty(v=>v||rows[0]?.id||'')}}
  async function loadCommunity(){if(!selectedNeighborhood){setDashboard(null);setDevices([]);setMaintenance([]);setParticipants([]);return}const[d,dev,m,part]=await Promise.all([neon.rpc('get_community_dashboard',{p_neighborhood_id:selectedNeighborhood}),neon.rpc('get_community_devices',{p_neighborhood_id:selectedNeighborhood}),neon.rpc('get_community_maintenance',{p_neighborhood_id:selectedNeighborhood}),neon.rpc('get_community_participants',{p_neighborhood_id:selectedNeighborhood})]);if(d.error){setDashboard(null);setMessage('Ative a participação de uma propriedade neste bairro ou use um perfil administrativo autorizado.')}else setDashboard(d.data as CommunityDashboard);if(!dev.error){const rows=(dev.data||[]) as CommunityDevice[];setDevices(rows);setRouteDevice(v=>v||rows.find(x=>x.device_type==='camera')?.device_id||'');setMaintenanceDevice(v=>v||rows[0]?.device_id||'')}else setDevices([]);if(!m.error)setMaintenance((m.data||[]) as Maintenance[]);else setMaintenance([]);if(!part.error)setParticipants((part.data||[]) as Participant[]);else setParticipants([])}
  async function loadPath(){if(!selectedProperty){setPath([]);return}const r=await neon.rpc('get_path_to_property_points',{p_property_id:selectedProperty});if(r.error)setPath([]);else setPath((r.data||[]) as PathPoint[])}
  async function activate(){if(!selectedProperty)return;setSaving(true);setMessage('');try{const r=await neon.rpc('activate_my_community_participation',{p_property_id:selectedProperty,p_route_points_enabled:routeEnabled,p_community_alerts_enabled:alertsEnabled});if(r.error)return setMessage(r.error.message.includes('property_owner_required')?'Somente o proprietário pode ativar a participação da fazenda.':'Não foi possível ativar a participação.');setMessage('Propriedade ativada no Community. Câmeras privadas continuam fora do compartilhamento.');await loadCommunity();await loadPath()}finally{setSaving(false)}}
  async function savePreferences(){if(!selectedProperty)return;setSaving(true);try{const r=await neon.rpc('set_my_community_preferences',{p_property_id:selectedProperty,p_route_points_enabled:routeEnabled,p_community_alerts_enabled:alertsEnabled});setMessage(r.error?'Somente o proprietário pode alterar essas preferências.':'Preferências Community atualizadas.');if(!r.error){await loadCommunity();await loadPath()}}finally{setSaving(false)}}
  async function leave(){if(!selectedProperty)return;setSaving(true);try{const r=await neon.rpc('leave_community',{p_property_id:selectedProperty});setMessage(r.error?'Somente o proprietário pode sair do Community.':'Participação encerrada e pontos de rota desativados.');if(!r.error){await loadCommunity();setPath([])}}finally{setSaving(false)}}
  async function saveRoutePoint(){if(!selectedProperty||!routeDevice)return;setSaving(true);try{const r=await neon.rpc('set_my_community_route_point',{p_property_id:selectedProperty,p_device_id:routeDevice,p_enabled:true,p_sequence_no:routeSequence});setMessage(r.error?'Use somente câmera comunitária do mesmo bairro e uma propriedade ativa no Community.':'Ponto comunitário adicionado ao caminho.');if(!r.error)await loadPath()}finally{setSaving(false)}}
  async function reportMaintenance(e:FormEvent){e.preventDefault();if(!maintenanceDevice||!maintenanceTitle.trim())return;setSaving(true);try{const r=await neon.rpc('report_community_maintenance',{p_device_id:maintenanceDevice,p_title:maintenanceTitle.trim(),p_description:maintenanceDescription.trim()||null,p_priority:maintenancePriority});setMessage(r.error?'Não foi possível registrar a manutenção.':'Solicitação de manutenção registrada.');if(!r.error){setMaintenanceTitle('');setMaintenanceDescription('');await loadCommunity()}}finally{setSaving(false)}}
  async function updateMaintenance(id:string,status:string){setSaving(true);try{const r=await neon.rpc('update_community_maintenance_status',{p_maintenance_id:id,p_status:status});setMessage(r.error?'Apenas Admin do bairro/organização ou técnico autorizado pode alterar o status.':'Status da manutenção atualizado.');if(!r.error)await loadCommunity()}finally{setSaving(false)}}
  async function saveRules(){if(!selectedNeighborhood)return;setSaving(true);try{const r=await neon.rpc('set_community_rules',{p_neighborhood_id:selectedNeighborhood,p_community_events_visible:communityEventsVisible,p_route_points_enabled:communityRouteEnabled});setMessage(r.error?'Somente Admin do bairro/organização pode alterar regras comunitárias.':'Regras do bairro atualizadas; compartilhamento privado permanece proibido.');if(!r.error)await loadCommunity()}finally{setSaving(false)}}
  useEffect(()=>{void loadBase()},[]);useEffect(()=>{void loadCommunity()},[selectedNeighborhood]);useEffect(()=>{void loadPath()},[selectedProperty]);
  return <section id="community-center"><div className="section-heading"><div><span className="eyebrow">SEC-090</span><h2>Community · Bairro Rural Conectado</h2></div>{dashboard&&<div className="structure-counts"><span>{dashboard.active_properties} propriedades</span><span>{dashboard.online_cameras}/{dashboard.community_cameras} câmeras online</span><span>{dashboard.open_maintenance} manutenções</span></div>}</div>{message&&<div className="structure-message">{message}</div>}
    <div className="community-selectors"><label>Bairro<select value={selectedNeighborhood} onChange={e=>setSelectedNeighborhood(e.target.value)}><option value="">Selecione</option>{neighborhoods.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Minha propriedade<select value={selectedProperty} onChange={e=>setSelectedProperty(e.target.value)}><option value="">Selecione</option>{propertyOptions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
    <div className="community-grid"><article className="structure-card"><strong>Participação da propriedade</strong><p>Adesão é opt-in do proprietário. Participar do bairro não compartilha câmeras privadas.</p><label className="check-row"><input type="checkbox" checked={routeEnabled} onChange={e=>setRouteEnabled(e.target.checked)}/> Caminho com pontos comunitários</label><label className="check-row"><input type="checkbox" checked={alertsEnabled} onChange={e=>setAlertsEnabled(e.target.checked)}/> Alertas comunitários</label><div className="button-row"><button className="primary" disabled={saving||!selectedProperty} onClick={()=>void activate()}>Ativar</button><button className="secondary" disabled={saving||!selectedProperty} onClick={()=>void savePreferences()}>Salvar</button><button className="danger-lite" disabled={saving||!selectedProperty} onClick={()=>void leave()}>Sair</button></div></article>
    <article className="structure-card"><strong>Caminho até minha propriedade</strong><p>Somente câmeras comunitárias explicitamente selecionadas aparecem neste caminho.</p><label>Ponto comunitário<select value={routeDevice} onChange={e=>setRouteDevice(e.target.value)}><option value="">Selecione</option>{cameras.map(d=><option key={d.device_id} value={d.device_id}>{d.name} · {d.status}</option>)}</select></label><label>Ordem<input type="number" min={0} max={1000} value={routeSequence} onChange={e=>setRouteSequence(Number(e.target.value))}/></label><button className="primary" disabled={saving||!routeDevice||!selectedProperty} onClick={()=>void saveRoutePoint()}>Adicionar ponto</button></article>
    <article className="structure-card"><strong>Regras do bairro</strong><p>Controle administrativo. A regra de dispositivo privado é fixa e não pode ser habilitada.</p><label className="check-row"><input type="checkbox" checked={communityEventsVisible} onChange={e=>setCommunityEventsVisible(e.target.checked)}/> Eventos comunitários visíveis</label><label className="check-row"><input type="checkbox" checked={communityRouteEnabled} onChange={e=>setCommunityRouteEnabled(e.target.checked)}/> Rotas comunitárias habilitadas</label><span className="locked-rule">🔒 Câmeras privadas: nunca compartilhadas pelo Community</span><button className="secondary" disabled={saving||!selectedNeighborhood} onClick={()=>void saveRules()}>Salvar regras</button></article></div>
    <div className="community-workspace"><div className="community-panel"><h3>Pontos autorizados do caminho</h3>{path.length?path.map(p=><div className="community-row" key={`${p.point_type}-${p.sequence_no}-${p.device_id||'property'}`}><div><strong>{p.name}</strong><small>{p.point_type==='property'?'Destino da propriedade':'Câmera comunitária'} · {p.status}</small></div><span>#{p.sequence_no}</span></div>):<p className="empty-state">Nenhum caminho autorizado configurado.</p>}</div><div className="community-panel"><h3>Dispositivos comunitários</h3>{devices.length?devices.map(d=><div className="community-row" key={d.device_id}><div><strong>{d.name}</strong><small>{d.device_type} · {d.status}</small></div><span>{d.latitude!=null?'geo':'—'}</span></div>):<p className="empty-state">Nenhum dispositivo comunitário visível.</p>}</div></div>
    <div className="community-workspace"><form className="community-panel" onSubmit={reportMaintenance}><h3>Reportar manutenção</h3><label>Dispositivo<select value={maintenanceDevice} onChange={e=>setMaintenanceDevice(e.target.value)}><option value="">Selecione</option>{devices.map(d=><option key={d.device_id} value={d.device_id}>{d.name}</option>)}</select></label><label>Título<input maxLength={160} value={maintenanceTitle} onChange={e=>setMaintenanceTitle(e.target.value)} placeholder="Ex.: câmera sem imagem"/></label><label>Descrição<textarea rows={3} maxLength={4000} value={maintenanceDescription} onChange={e=>setMaintenanceDescription(e.target.value)}/></label><label>Prioridade<select value={maintenancePriority} onChange={e=>setMaintenancePriority(e.target.value)}><option value="attention">Atenção</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><button className="primary" disabled={saving||!maintenanceDevice||!maintenanceTitle.trim()}>Registrar</button></form><div className="community-panel"><h3>Manutenção comunitária</h3>{maintenance.length?maintenance.map(m=><div className="maintenance-row" key={m.id}><div><strong>{m.title}</strong><small>{m.device_name} · {m.priority} · {m.status}</small></div>{!['resolved','closed'].includes(m.status)&&<div className="button-row"><button className="secondary tiny" disabled={saving} onClick={()=>void updateMaintenance(m.id,'in_progress')}>Em andamento</button><button className="secondary tiny" disabled={saving} onClick={()=>void updateMaintenance(m.id,'resolved')}>Resolver</button></div>}</div>):<p className="empty-state">Sem manutenção aberta.</p>}</div></div>
    {participants.length>0&&<div className="community-panel"><h3>Participantes · visão administrativa</h3>{participants.map(p=><div className="community-row" key={p.property_id}><div><strong>{p.property_name}</strong><small>{p.status} · rota {p.route_points_enabled?'on':'off'} · alertas {p.community_alerts_enabled?'on':'off'}</small></div></div>)}</div>}
    <div className="community-guard"><strong>Separação obrigatória</strong><p>Community exibe apenas infraestrutura comunitária e preferências explícitas. Nenhum Admin de bairro recebe acesso às câmeras, gravações, eventos ou ativos privados de uma fazenda por causa da participação no bairro.</p></div>
  </section>
}
