import { FormEvent, useEffect, useState } from 'react';
import { neon } from './lib/neon';
import './evidence.css';

type EvidenceRow = { id:string; evidence_type:string; sha256:string; manifest_hash:string; mime_type:string; file_size_bytes:number|null; integrity_status:'unverified'|'verified'|'mismatch'|'sealed'; captured_at:string; retained_until:string|null; legal_hold:boolean; retention_reason:string; incident_id:string|null; event_id:string|null; recording_id:string|null; registered_at:string; verified_at:string|null; action_count:number|string };
type RecordingRow = { id:string; device_id:string; device_name:string; device_type:string; community_shared:boolean; starts_at:string; ends_at:string; retained_until:string|null; sha256:string; mime_type:string; file_size_bytes:number|null; integrity_status:string; verified_at:string|null };
type IncidentRow = { id:string; title:string; status:string };
type TimelineRow = { id:string; action_type:string; details:Record<string,unknown>; previous_action_hash:string|null; action_hash:string; created_at:string };

export function EvidenceVault(){
  const [evidence,setEvidence]=useState<EvidenceRow[]>([]); const [recordings,setRecordings]=useState<RecordingRow[]>([]); const [incidents,setIncidents]=useState<IncidentRow[]>([]); const [timeline,setTimeline]=useState<TimelineRow[]>([]);
  const [selected,setSelected]=useState(''); const [sourceType,setSourceType]=useState<'incident'|'recording'>('incident'); const [sourceId,setSourceId]=useState('');
  const [type,setType]=useState('video'); const [storageKey,setStorageKey]=useState(''); const [sha,setSha]=useState(''); const [mime,setMime]=useState('video/mp4'); const [size,setSize]=useState(''); const [capturedAt,setCapturedAt]=useState(''); const [retainedUntil,setRetainedUntil]=useState(''); const [reason,setReason]=useState('retenção operacional do incidente'); const [legalHold,setLegalHold]=useState(false);
  const [verifyHash,setVerifyHash]=useState(''); const [exportType,setExportType]=useState<'download'|'share'>('download'); const [purpose,setPurpose]=useState(''); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);

  async function load(){ const [e,r,i]=await Promise.all([neon.rpc('get_evidence_vault'),neon.rpc('get_recordings_catalog'),neon.rpc('get_incident_feed',{p_limit:200})]); if(e.error||r.error||i.error){setMessage('Não foi possível carregar o Evidence Vault.');return;} const ev=(e.data||[]) as EvidenceRow[]; setEvidence(ev); setRecordings((r.data||[]) as RecordingRow[]); setIncidents((i.data||[]) as IncidentRow[]); setSelected(v=>v||ev[0]?.id||''); }
  async function loadTimeline(id:string){ if(!id){setTimeline([]);return;} const r=await neon.rpc('get_evidence_timeline',{p_evidence_id:id}); if(!r.error)setTimeline((r.data||[]) as TimelineRow[]); }
  async function register(event:FormEvent){event.preventDefault();setSaving(true);setMessage('');try{const result=await neon.rpc('register_evidence_manifest',{p_incident_id:sourceType==='incident'?sourceId:null,p_event_id:null,p_recording_id:sourceType==='recording'?sourceId:null,p_evidence_type:type,p_storage_key:storageKey,p_sha256:sha,p_captured_at:new Date(capturedAt).toISOString(),p_retained_until:legalHold||!retainedUntil?null:new Date(retainedUntil).toISOString(),p_mime_type:mime,p_file_size_bytes:size?Number(size):null,p_original_filename:null,p_retention_reason:reason,p_legal_hold:legalHold}); if(result.error){setMessage(result.error.message.includes('evidence_scope_mismatch')?'As fontes pertencem a escopos diferentes.':'Não foi possível registrar o manifesto.');return;} setStorageKey('');setSha('');setSize('');setMessage('Manifesto registrado. O arquivo físico continua privado e desacoplado.');await load();}finally{setSaving(false)}}
  async function verify(){if(!selected||!verifyHash)return;setSaving(true);try{const r=await neon.rpc('verify_evidence_hash',{p_evidence_id:selected,p_observed_sha256:verifyHash});setMessage(r.error?'Não foi possível verificar o hash.':r.data==='verified'?'Integridade confirmada.':'Hash divergente: exportação bloqueada.');await load();await loadTimeline(selected);}finally{setSaving(false)}}
  async function requestExport(){if(!selected||!purpose.trim())return;setSaving(true);try{const r=await neon.rpc('request_evidence_export',{p_evidence_id:selected,p_request_type:exportType,p_purpose:purpose.trim()});setMessage(r.error?'Solicitação não permitida.':'Solicitação auditada. Status: blocked_storage até o storage privado ser configurado.');setPurpose('');await loadTimeline(selected);}finally{setSaving(false)}}
  useEffect(()=>{void load()},[]); useEffect(()=>{void loadTimeline(selected)},[selected]);
  const current=evidence.find(e=>e.id===selected);
  return <section id="evidence-vault"><div className="section-heading"><div><span className="eyebrow">SEC-051 / SEC-052</span><h2>Evidence Vault</h2></div><div className="structure-counts"><span>{evidence.length} evidências</span><span>{recordings.length} gravações</span><span>SHA-256 + custódia</span></div></div>{message&&<div className="structure-message">{message}</div>}
    <div className="evidence-grid"><form className="structure-card" onSubmit={register}><strong>Registrar manifesto</strong><p>Registra metadados e integridade. Nunca informe URL pública; use somente uma chave opaca do storage privado.</p><label>Fonte<select value={sourceType} onChange={e=>{setSourceType(e.target.value as 'incident'|'recording');setSourceId('')}}><option value="incident">Incidente</option><option value="recording">Gravação</option></select></label><label>{sourceType==='incident'?'Incidente':'Gravação'}<select required value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Selecione</option>{sourceType==='incident'?incidents.map(i=><option key={i.id} value={i.id}>{i.title} · {i.status}</option>):recordings.map(r=><option key={r.id} value={r.id}>{r.device_name} · {new Date(r.starts_at).toLocaleString('pt-BR')}</option>)}</select></label><div className="field-row evidence-row"><label>Tipo<input required value={type} onChange={e=>setType(e.target.value)}/></label><label>MIME<input required value={mime} onChange={e=>setMime(e.target.value)}/></label></div><label>Storage key opaca<input required placeholder="org/.../arquivo.enc" value={storageKey} onChange={e=>setStorageKey(e.target.value)}/></label><label>SHA-256<input required minLength={64} maxLength={64} value={sha} onChange={e=>setSha(e.target.value.toLowerCase())}/></label><div className="field-row evidence-row"><label>Capturado em<input type="datetime-local" required value={capturedAt} onChange={e=>setCapturedAt(e.target.value)}/></label><label>Tamanho (bytes)<input type="number" min="1" value={size} onChange={e=>setSize(e.target.value)}/></label></div><label>Retenção até<input type="datetime-local" disabled={legalHold} required={!legalHold} value={retainedUntil} onChange={e=>setRetainedUntil(e.target.value)}/></label><label>Motivo da retenção<input required value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="evidence-check"><input type="checkbox" checked={legalHold} onChange={e=>setLegalHold(e.target.checked)}/> Legal hold</label><button className="primary" disabled={saving||!sourceId}>Registrar manifesto</button></form>
      <div className="structure-card"><strong>Cofre sanitizado</strong><p>O navegador nunca recebe storage_key. Selecione uma evidência para ver integridade, custódia e solicitar exportação.</p><div className="evidence-list">{evidence.length?evidence.map(e=><button type="button" key={e.id} className={selected===e.id?'selected':''} onClick={()=>setSelected(e.id)}><span><strong>{e.evidence_type}</strong><small>{new Date(e.captured_at).toLocaleString('pt-BR')}</small></span><span className={`integrity integrity-${e.integrity_status}`}>{e.integrity_status}</span></button>):<small>Nenhuma evidência registrada.</small>}</div></div>
      <div className="structure-card"><strong>Integridade e exportação</strong>{current?<><p>SHA-256: <code>{current.sha256}</code></p><p>Manifesto: <code>{current.manifest_hash}</code></p><p>Retenção: {current.legal_hold?'Legal hold':current.retained_until?new Date(current.retained_until).toLocaleString('pt-BR'):'não definida'}</p><label>Hash observado<input value={verifyHash} onChange={e=>setVerifyHash(e.target.value.toLowerCase())}/></label><button type="button" className="secondary" disabled={saving||verifyHash.length!==64} onClick={()=>void verify()}>Verificar integridade</button><label>Solicitação<select value={exportType} onChange={e=>setExportType(e.target.value as 'download'|'share')}><option value="download">Download</option><option value="share">Compartilhamento</option></select></label><label>Finalidade<input value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><button type="button" className="secondary" disabled={saving||!purpose.trim()} onClick={()=>void requestExport()}>Solicitar</button><div className="evidence-timeline"><strong>Cadeia de custódia</strong>{timeline.map(t=><div key={t.id}><span>{t.action_type}</span><small>{new Date(t.created_at).toLocaleString('pt-BR')} · {t.action_hash.slice(0,12)}…</small></div>)}</div></>:<p>Selecione uma evidência.</p>}</div>
    </div><div className="map-privacy-note"><strong>Storage ainda não configurado:</strong> pedidos de download/compartilhamento ficam bloqueados e auditados. Nenhum link público é criado nesta fase.</div></section>;
}
