import { FormEvent, useEffect, useState } from 'react';
import { neon } from './lib/neon';
import './sos.css';

type Property={id:string;name:string};
type SOSRow={id:string;property_id:string;property_name:string;requested_by_name:string;incident_id:string;occurrence:string;severity:string;status:'open'|'acknowledged'|'closed'|'cancelled';latitude:number;longitude:number;location_accuracy_m:number|null;public_integration_status:string;created_at:string;acknowledged_at:string|null;closed_at:string|null;evidence_count:number|string};

export function SOSCenter(){
  const[properties,setProperties]=useState<Property[]>([]);const[rows,setRows]=useState<SOSRow[]>([]);const[propertyId,setPropertyId]=useState('');const[occurrence,setOccurrence]=useState('');const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);const[closeNote,setCloseNote]=useState('Atendimento concluído e registrado.');
  async function load(){const[p,s]=await Promise.all([neon.from('properties').select('id,name'),neon.rpc('get_ifarm_sos_feed')]);if(p.error||s.error){setMessage('Não foi possível carregar o iFarm SOS.');return;}const props=(p.data||[]) as Property[];setProperties(props);setRows((s.data||[]) as SOSRow[]);setPropertyId(v=>v||props[0]?.id||'');}
  function getLocation():Promise<{lat:number|null;lon:number|null;accuracy:number|null}>{return new Promise(resolve=>{if(!navigator.geolocation)return resolve({lat:null,lon:null,accuracy:null});navigator.geolocation.getCurrentPosition(pos=>resolve({lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy}),()=>resolve({lat:null,lon:null,accuracy:null}),{enableHighAccuracy:true,timeout:5000,maximumAge:30000})})}
  async function start(event:FormEvent){event.preventDefault();if(!propertyId||occurrence.trim().length<3)return;setSaving(true);setMessage('');try{const location=await getLocation();const r=await neon.rpc('start_ifarm_sos',{p_property_id:propertyId,p_occurrence:occurrence.trim(),p_latitude:location.lat,p_longitude:location.lon,p_accuracy_m:location.accuracy});if(r.error){setMessage(r.error.message.includes('location_required')?'A propriedade não tem localização cadastrada e o GPS não foi fornecido.':'Não foi possível iniciar o SOS.');return;}setOccurrence('');setMessage('SOS registrado internamente. Nenhuma autoridade pública foi acionada automaticamente.');await load();}finally{setSaving(false)}}
  async function acknowledge(id:string){setSaving(true);try{const r=await neon.rpc('acknowledge_ifarm_sos',{p_sos_id:id});setMessage(r.error?'Seu perfil não pode reconhecer este SOS.':'SOS reconhecido e incidente colocado em investigação.');await load();}finally{setSaving(false)}}
  async function close(id:string){setSaving(true);try{const r=await neon.rpc('close_ifarm_sos',{p_sos_id:id,p_note:closeNote.trim()});setMessage(r.error?'Não foi possível encerrar o SOS.':'SOS encerrado com nota operacional.');await load();}finally{setSaving(false)}}
  useEffect(()=>{void load()},[]);
  const active=rows.filter(r=>r.status==='open'||r.status==='acknowledged').length;
  return <section id="ifarm-sos"><div className="section-heading"><div><span className="eyebrow">SEC-060</span><h2>iFarm SOS</h2></div><div className="structure-counts"><span>{rows.length} registros</span><span>{active} ativos</span><span>integração pública: não configurada</span></div></div>{message&&<div className="structure-message">{message}</div>}<div className="sos-layout"><form className="sos-trigger" onSubmit={start}><strong>Pedido de assistência</strong><p>Cria um registro interno crítico e um incidente operacional. Não chama polícia, bombeiros ou outro órgão automaticamente.</p><label>Propriedade<select required value={propertyId} onChange={e=>setPropertyId(e.target.value)}><option value="">Selecione</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>O que está acontecendo?<textarea required minLength={3} maxLength={2000} rows={4} value={occurrence} onChange={e=>setOccurrence(e.target.value)}/></label><button className="sos-button" disabled={saving||!propertyId||occurrence.trim().length<3}>ATIVAR iFARM SOS</button><small>O sistema tentará usar sua localização atual. Se o GPS não estiver disponível, usará o ponto cadastrado da propriedade.</small></form><div className="structure-card"><strong>Atendimentos recentes</strong><div className="sos-list">{rows.length?rows.map(row=><div key={row.id} className={`sos-item sos-${row.status}`}><div><strong>{row.property_name}</strong><p>{row.occurrence}</p><small>{row.requested_by_name} · {new Date(row.created_at).toLocaleString('pt-BR')}</small><small>Local: {Number(row.latitude).toFixed(5)}, {Number(row.longitude).toFixed(5)} · evidências: {row.evidence_count}</small><small>Integração pública: {row.public_integration_status}</small></div><div className="sos-actions"><span>{row.status}</span>{row.status==='open'&&<button className="secondary" disabled={saving} onClick={()=>void acknowledge(row.id)}>Reconhecer</button>}{row.status!=='closed'&&row.status!=='cancelled'&&<button className="secondary" disabled={saving} onClick={()=>void close(row.id)}>Encerrar</button>}</div></div>):<small>Nenhum SOS visível no seu escopo.</small>}</div><label>Nota padrão de encerramento<input value={closeNote} onChange={e=>setCloseNote(e.target.value)}/></label></div></div></section>;
}
