-- SEC-051/052 Evidence Vault. Aplicar primeiro em DEV. Sem storage público.
ALTER TABLE evidence ADD COLUMN recording_id uuid REFERENCES recordings(id), ADD COLUMN mime_type text, ADD COLUMN file_size_bytes bigint, ADD COLUMN storage_provider text NOT NULL DEFAULT 'pending', ADD COLUMN original_filename text, ADD COLUMN integrity_status text NOT NULL DEFAULT 'unverified', ADD COLUMN verified_at timestamptz, ADD COLUMN verified_by uuid REFERENCES app_users(id), ADD COLUMN retention_reason text, ADD COLUMN legal_hold boolean NOT NULL DEFAULT false, ADD COLUMN manifest_hash text, ADD COLUMN registered_by uuid REFERENCES app_users(id), ADD COLUMN sealed_at timestamptz;
ALTER TABLE evidence ALTER COLUMN sha256 SET NOT NULL;
ALTER TABLE evidence ADD CONSTRAINT evidence_sha256_format CHECK (sha256 ~ '^[0-9a-f]{64}$'), ADD CONSTRAINT evidence_file_size_positive CHECK (file_size_bytes IS NULL OR file_size_bytes > 0), ADD CONSTRAINT evidence_integrity_status_allowed CHECK (integrity_status IN ('unverified','verified','mismatch','sealed')), ADD CONSTRAINT evidence_has_source CHECK (incident_id IS NOT NULL OR event_id IS NOT NULL OR recording_id IS NOT NULL), ADD CONSTRAINT evidence_retention_defined CHECK (retained_until IS NOT NULL OR legal_hold), ADD CONSTRAINT evidence_storage_key_opaque CHECK (position('://' in storage_key)=0);
CREATE UNIQUE INDEX evidence_org_storage_key_uq ON evidence(organization_id,storage_key);
CREATE INDEX evidence_incident_idx ON evidence(incident_id) WHERE incident_id IS NOT NULL; CREATE INDEX evidence_event_idx ON evidence(event_id) WHERE event_id IS NOT NULL; CREATE INDEX evidence_recording_idx ON evidence(recording_id) WHERE recording_id IS NOT NULL;
ALTER TABLE recordings ADD COLUMN sha256 text, ADD COLUMN mime_type text, ADD COLUMN file_size_bytes bigint, ADD COLUMN storage_provider text NOT NULL DEFAULT 'pending', ADD COLUMN integrity_status text NOT NULL DEFAULT 'unverified', ADD COLUMN verified_at timestamptz, ADD COLUMN verified_by uuid REFERENCES app_users(id);
ALTER TABLE recordings ALTER COLUMN sha256 SET NOT NULL;
ALTER TABLE recordings ADD CONSTRAINT recordings_sha256_format CHECK (sha256 ~ '^[0-9a-f]{64}$'), ADD CONSTRAINT recordings_file_size_positive CHECK (file_size_bytes IS NULL OR file_size_bytes > 0), ADD CONSTRAINT recordings_integrity_status_allowed CHECK (integrity_status IN ('unverified','verified','mismatch')), ADD CONSTRAINT recordings_storage_key_opaque CHECK (position('://' in storage_key)=0);
CREATE UNIQUE INDEX recordings_org_storage_key_uq ON recordings(organization_id,storage_key);
CREATE TABLE evidence_actions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE CASCADE,actor_user_id uuid REFERENCES app_users(id),action_type text NOT NULL,details jsonb NOT NULL DEFAULT '{}'::jsonb,previous_action_hash text,action_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT evidence_actions_hash_format CHECK(action_hash~'^[0-9a-f]{64}$'),CONSTRAINT evidence_actions_previous_hash_format CHECK(previous_action_hash IS NULL OR previous_action_hash~'^[0-9a-f]{64}$'));
CREATE INDEX evidence_actions_evidence_time_idx ON evidence_actions(evidence_id,created_at,id);
CREATE TABLE evidence_export_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE CASCADE,requester_user_id uuid NOT NULL REFERENCES app_users(id),request_type text NOT NULL CHECK(request_type IN('download','share')),purpose text NOT NULL,status text NOT NULL DEFAULT 'blocked_storage' CHECK(status IN('blocked_storage','requested','approved','rejected','fulfilled','expired')),created_at timestamptz NOT NULL DEFAULT now(),decided_at timestamptz,decided_by uuid REFERENCES app_users(id),fulfilled_at timestamptz);
CREATE INDEX evidence_export_requests_evidence_idx ON evidence_export_requests(evidence_id,created_at DESC);
ALTER TABLE evidence_actions ENABLE ROW LEVEL SECURITY; ALTER TABLE evidence_export_requests ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION app_can_manage_evidence_scope(p_organization_id uuid,p_neighborhood_id uuid,p_property_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO public,auth AS $$ SELECT app_is_platform_admin() OR EXISTS(SELECT 1 FROM memberships m JOIN app_users u ON u.id=m.user_id WHERE u.auth_user_id=NULLIF(auth.user_id(),'')::uuid AND u.status='active' AND m.status='active' AND m.organization_id=p_organization_id AND (m.role='admin_organization' OR (p_property_id IS NOT NULL AND m.property_id=p_property_id AND m.role IN('owner','monitoring')) OR (p_property_id IS NULL AND p_neighborhood_id IS NOT NULL AND m.neighborhood_id=p_neighborhood_id AND m.role IN('admin_neighborhood','monitoring')))) $$;
ALTER POLICY evidence_scope_read ON evidence USING(organization_id IS NOT NULL AND (incident_id IS NULL OR EXISTS(SELECT 1 FROM incidents i WHERE i.id=evidence.incident_id AND app_has_scope_access(i.organization_id,i.neighborhood_id,i.property_id))) AND (event_id IS NULL OR EXISTS(SELECT 1 FROM security_events e WHERE e.id=evidence.event_id AND app_has_scope_access(e.organization_id,e.neighborhood_id,e.property_id))) AND (recording_id IS NULL OR EXISTS(SELECT 1 FROM recordings r JOIN devices d ON d.id=r.device_id WHERE r.id=evidence.recording_id AND app_has_scope_access(r.organization_id,d.neighborhood_id,d.property_id))) AND (incident_id IS NOT NULL OR event_id IS NOT NULL OR recording_id IS NOT NULL));
REVOKE SELECT ON evidence,recordings FROM authenticated,anonymous; REVOKE INSERT,UPDATE,DELETE ON evidence,recordings,evidence_actions,evidence_export_requests FROM authenticated,anonymous;
CREATE POLICY evidence_actions_scope_read ON evidence_actions FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM evidence e WHERE e.id=evidence_actions.evidence_id AND ((e.incident_id IS NOT NULL AND EXISTS(SELECT 1 FROM incidents i WHERE i.id=e.incident_id AND app_has_scope_access(i.organization_id,i.neighborhood_id,i.property_id))) OR (e.event_id IS NOT NULL AND EXISTS(SELECT 1 FROM security_events se WHERE se.id=e.event_id AND app_has_scope_access(se.organization_id,se.neighborhood_id,se.property_id))) OR (e.recording_id IS NOT NULL AND EXISTS(SELECT 1 FROM recordings r JOIN devices d ON d.id=r.device_id WHERE r.id=e.recording_id AND app_has_scope_access(r.organization_id,d.neighborhood_id,d.property_id))))));
CREATE POLICY evidence_export_requests_scope_read ON evidence_export_requests FOR SELECT TO authenticated USING(requester_user_id=app_current_user_id()); GRANT SELECT ON evidence_actions,evidence_export_requests TO authenticated;
-- Funções completas de DEV: resolve_evidence_scope, append_evidence_action, register_evidence_manifest, verify_evidence_hash,
-- extend_evidence_retention, set_evidence_legal_hold, request_evidence_export, get_evidence_vault,
-- get_evidence_timeline, register_recording_manifest, verify_recording_hash e get_recordings_catalog.
-- A implementação canônica dessas funções deve ser promovida DEV→STAGE somente após revisão da migration e teste automatizado.
